"""Initial NovelAgent schema."""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("projects", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("path", sa.String(1024), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("path"))
    op.create_table("chapters", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("sequence", sa.Integer(), nullable=False), sa.Column("status", sa.String(32), nullable=False))
    op.create_table("scenes", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("chapter_id", sa.Integer(), sa.ForeignKey("chapters.id"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("sequence", sa.Integer(), nullable=False), sa.Column("pov", sa.String(255)), sa.Column("location", sa.String(255)), sa.Column("current_revision_id", sa.Integer()), sa.Column("status", sa.String(32), nullable=False))
    op.create_table("scene_revisions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("scene_id", sa.Integer(), sa.ForeignKey("scenes.id"), nullable=False), sa.Column("base_revision_id", sa.Integer()), sa.Column("content", sa.Text(), nullable=False), sa.Column("source", sa.String(32), nullable=False), sa.Column("content_hash", sa.String(64), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("claim_candidates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("scene_id", sa.Integer(), sa.ForeignKey("scenes.id"), nullable=False), sa.Column("subject", sa.String(255), nullable=False), sa.Column("predicate", sa.String(255), nullable=False), sa.Column("object_value", sa.String(255), nullable=False), sa.Column("modality", sa.String(32), nullable=False), sa.Column("source_start", sa.Integer(), nullable=False), sa.Column("source_end", sa.Integer(), nullable=False), sa.Column("source_text", sa.Text(), nullable=False), sa.Column("confidence", sa.Float(), nullable=False), sa.Column("entity_confidence", sa.Float(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("canon_claims", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("subject", sa.String(255), nullable=False), sa.Column("predicate", sa.String(255), nullable=False), sa.Column("object_value", sa.String(255), nullable=False), sa.Column("modality", sa.String(32), nullable=False), sa.Column("source_scene_id", sa.Integer()), sa.Column("source_start", sa.Integer(), nullable=False), sa.Column("source_end", sa.Integer(), nullable=False), sa.Column("confirmed", sa.Boolean(), nullable=False))
    op.create_table("generation_workspaces", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("scene_id", sa.Integer(), sa.ForeignKey("scenes.id"), nullable=False), sa.Column("base_revision_id", sa.Integer()), sa.Column("content", sa.Text(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("context_manifest", sa.JSON(), nullable=True), sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_table("items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("unique_item", sa.Boolean(), nullable=False), sa.Column("current_holder", sa.String(255)), sa.Column("current_state", sa.String(32), nullable=False))
    op.create_table("item_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("item_id", sa.Integer(), sa.ForeignKey("items.id"), nullable=False), sa.Column("event_type", sa.String(32), nullable=False), sa.Column("from_holder", sa.String(255)), sa.Column("to_holder", sa.String(255)), sa.Column("scene_id", sa.Integer()), sa.Column("confirmed", sa.Boolean(), nullable=False))
    op.create_table("shadow_entities", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("display_name", sa.String(255), nullable=False), sa.Column("canonical_character", sa.String(255)), sa.Column("revealed_scene_id", sa.Integer()))
    op.create_table("import_jobs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id"), nullable=False), sa.Column("source_path", sa.String(1024), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("checkpoint", sa.Integer(), nullable=False))
    op.create_table("model_invocations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("task_type", sa.String(64), nullable=False), sa.Column("tier", sa.String(8), nullable=False), sa.Column("model", sa.String(255), nullable=False), sa.Column("context_manifest", sa.JSON(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("commit_journal", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("revision_id", sa.Integer(), nullable=False), sa.Column("content_hash", sa.String(64), nullable=False), sa.Column("file_path", sa.String(1024), nullable=False), sa.Column("file_status", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("pending_projections", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("revision_id", sa.Integer(), nullable=False), sa.Column("projection_type", sa.String(32), nullable=False), sa.Column("status", sa.String(32), nullable=False))
    op.create_table("generation_runs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("scene_id", sa.Integer(), sa.ForeignKey("scenes.id"), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("prompt", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))


def downgrade() -> None:
    for table in ["generation_runs", "pending_projections", "commit_journal", "model_invocations", "import_jobs", "shadow_entities", "item_events", "items", "generation_workspaces", "canon_claims", "claim_candidates", "scene_revisions", "scenes", "chapters", "projects"]:
        op.drop_table(table)
