"""API Routers package."""
from . import (
    chapters,
    characters,
    claims,
    foreshadowings,
    generation,
    impact,
    imports,
    items,
    locations,
    patches,
    plots,
    projects,
    relationships,
    scenes,
    secrets,
    shadows,
    system,
    transitions,
    workspaces,
)

__all__ = [
    "chapters",
    "characters",
    "claims",
    "foreshadowings",
    "generation",
    "impact",
    "imports",
    "items",
    "locations",
    "patches",
    "plots",
    "projects",
    "relationships",
    "scenes",
    "secrets",
    "shadows",
    "system",
    "transitions",
    "workspaces",
]
